[pytest]
testpaths =
    test_api
    test_ui
python_files = test_*.py
python_functions = test_*
addopts = -ra
markers =
    api_foundation: API foundation smoke tests
    api_tms: TMS API tests
    ui_tms: TMS UI tests
    ui_foundation: browser foundation smoke tests
    smoke: smoke tests
    e2e: end-to-end tests
